### ISSUE TITLE
Testing version February 2020 v1.3.3 under Linux

### ISSUE THREAD

**Issue by edsz14** [J-ISIS/J-ISIS#16]
Tested under Linux Ubuntu/Mint 64-bits, current releases with Zulu JDK-FX AMD64 Java (both 8 and 11), but several problems occurred, not sure whether problems relate to Java-version or J-ISIS software. Some of them presented here : 

1. After creating a new database successfully it cannot be opened (while in the file-system all files are there) : 

org.unesco.jisis.corelib.exceptions.DbException: Error when opening the Database
    at org.unesco.jisis.corelib.client.RemoteDatabase.getDatabase(RemoteDatabase.java:104)
    at org.unesco.jisis.jisisutils.proxy.ClientDatabaseProxy.getDatabase(ClientDatabaseProxy.java:251)
[catch] at org.unesco.jisis.jisisutils.proxy.DirectConnectOpen$1.run(DirectConnectOpen.java:147)
    at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
    at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
    at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
    at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

2. Several existing PFTs tested in the existing demo-databases but getting :
Error Interpreting PFT
In fact many PFT's in the demo-databases need to be checked/corrected/cleaned.

3. DL-Example database :

Opening menu-option EDIT/Data Entry Worksheet :
A java.lang.NoClassDefFoundError exception has occurred.
    Click Show Details or see the messages.log file located in your /root/.jisis_suite/dev/var/log folder.

Creating new 'Advanced Worksheet Editor' : successfully saved but not included in worksheets list until after re-opening.

**Comment by jcd92410** [comment]
Thanks Egbert for reporting these issues under Linux
1) was it possible to open the created  database after restarting ?
2) maybe some of the PFT in the demo Databases are not in utf-8 Linux compatible format- try to open in an editor 
3) it may be a threading problem which is different under Linux
JC

Envoyé de mon iPhone

**Comment by edsz14** [comment]
No, also after restarting the newly created database does not open and gives now yet another error, which hopefully is a bit more revealing :

java.lang.NullPointerException
at org.unesco.jisis.corelib.client.ConnectionInfo.findDatabase(ConnectionInfo.java:72)
at org.unesco.jisis.mrudatabases.MRUDatabasesAction$MRUFilesMenu.menuItemActionPerformed(MRUDatabasesAction.java:199)
at org.unesco.jisis.mrudatabases.MRUDatabasesAction$MRUFilesMenu.access$100(MRUDatabasesAction.java:93)
at org.unesco.jisis.mrudatabases.MRUDatabasesAction$MRUFilesMenu$MyAction.actionPerformed(MRUDatabasesAction.java:150)
at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
at java.desktop/java.awt.Component.processEvent(Component.java:6400)
at java.desktop/java.awt.Container.processEvent(Container.java:2263)
at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)


I am attaching the files created for this database 'MULTINFO' (which by the way only makes sense as a test for creating a database). All text-files are in UTF8.     On Thursday, June 24, 2021, 10:30:08 AM GMT+2, Jean-Claude DAUPHIN ***@***.***> wrote:  
 
 

Thanks Egbert for reporting these issues under Linux
1) was it possible to open the created database after restarting ?
2) maybe some of the PFT in the demo Databases are not in utf-8 Linux compatible format- try to open in an editor 
3) it may be a threading problem which is different under Linux
JC

Envoyé de mon iPhone
